### PR TITLE
Improve width-dependent param names, allow min/max transposing

### LINKED ISSUE #16: Transpose min/max values
Would be great to be able to transpose the min/max values so the scaling effect was reversed for each of the metrics individually (size, leading, weight, etc).

### LINKED ISSUE #21: Improve Variable Names
The current default `minLineHeight` is `1.33` and default `maxLineHeight` is `1.25`. Unusual to have a `min` greater than the `max`. Maybe a typo?

### PR DESCRIPTION
**Pull request by tinymachine**
(Note: this is the first non-nominal PR I've submitted, so my apologies up front if anything I've done here is poor PR etiquette. If there's anything you wish I'd done differently, I'm all ears.)

## Improve width-dependent param names (closes #21)

Width-dependent parameter names have been updated to reflect their dependency on the container width:

Old Parameter Name|New Parameter Name
-|-
`minFontSize`|`minWidthFontSize`
`maxFontSize`|`maxWidthFontSize`
`minLineHeight`|`minWidthLineHeight`
`maxLineHeight`|`maxWidthLineHeight`
`minVariableGrade`|`minWidthVariableGrade`
`maxVariableGrade`|`maxWidthVariableGrade`

The old param names are still supported (see 5468aba027cc4db1daa26ba4f91b8dc5ae51322e). I added a test to `demo.html` to demonstrate this.

**Note: no added console warning.** In #21 we discussed including a console warning to notify devs if they use the legacy params, but I looked into it a bit and it seems like shipping browser console warnings in production-bound code is not a best-practice (not to mention the code for conditionally displaying the message would add to the script's size). I think it might make more sense to communicate the update in the readme. (There also may be no need to deprecate the old param names, since the code to handle it is minimal.)

## Allow for min/max transposing (closes #16)

The formulas (formulae?) for calculating font-size, line-height, and variable grade have been rewritten (and simplified a bit, I think) so that it doesn't matter whether the min or max setting is larger. I added a test to `demo.html` to demonstrate 'transposed' values for each of these attributes.

**Note:** @theorosendorf said the relationship between line-height and width is linear (https://github.com/glyphic-co/textblock/issues/21#issuecomment-466078040), but in my testing it didn't appear linear. (A test div with `minWidth: 400`, `maxWidth: 800`, `minLineHeight: 1`, and `maxLineHeight: 2` yielded a line-height of 1.2 at 600px wide, instead of an expected 1.5. But my test might have been flawed. FWIW.)

## ESLint and Prettier
In addition to these changes, I also integrated [ESLint](https://eslint.org) and [Prettier](https://prettier.io) into the project. You may be familiar with these tools; I find them really useful for catching JS errors and standardizing formatting respectively. I know adding these tools goes beyond the scope of this PR, but I thought it would be a useful addition to the dev experience (and will hopefully help keep future community-submitted PR's error-free and more consistent with your style preferences). (You can modify the linting and styling rules in the `.eslintrc.js` and `.prettierrc.js` files, respectively.)

(Again, as you may know, with these tools in place, you can enable automatic linting and formatting on save by using a code editor extension like [ESLint for VSCode](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint). No need to install a separate Prettier plugin, as I've set up Prettier to be integrated with ESLint.)

### CODE REVIEW

**Comment by theorosendorf** [comment]
Looks amazing from here. I should have time to take a proper look tomorrow. Thanks Mihira!

**Comment by theorosendorf** [comment]
This looks great to me although I may have missed something. @traviskochel – think you could take a peek?

**Comment by theorosendorf** [comment]
BTW, I’m no expert but I think this is fantastic PR etiquette @tinymachine.

**Comment by tinymachine** [comment]
Glad to hear it, @theorosendorf! Open to any feedback from @traviskochel too.

**Comment by traviskochel** [comment]
Looks good to me 👍

**Comment by theorosendorf** [comment]
Thanks @traviskochel! Will merge later when I can also make the release to master.

**Pull request merged**
