### PR TITLE
‼️ Important addendum to #38: make ESLint ignore minified files

### PR DESCRIPTION
**Pull request by tinymachine**
Without this, lint-staged will run `eslint --fix` whenever textblock.min.js is staged, which will prettify (decompress) it, which we definitely don't want! 

Sorry for missing this earlier, @theorosendorf! It looks like the 0.11.0 release was [affected by this](https://github.com/glyphic-co/textblock/blob/1a87dd8368eb455db0068617f53d58f22039b7ba/textblock.min.js). I've rebuilt the minified file in this PR (but note I haven't bumped the `pkg.version` number, which I'll leave up to you.

### CODE REVIEW

**Comment by theorosendorf** [comment]
K, thanks for catching that. Does your PR also include 0.11.0?

**Comment by tinymachine** [comment]
Yes, I pulled from the development branch last night before making these commits.

**Comment by theorosendorf** [comment]
Thanks @tinymachine! Was going to add you but thought I should ask first, would you like to be added as an admin for textblock?

**Comment by tinymachine** [comment]
I'm honored, @theorosendorf. I've never been an admin before; what kind of responsibilities do you envision it would entail? Just want to make sure I understand your expectations.

**Comment by theorosendorf** [comment]
No responsibilities, just easier to make a fix if you need.

**Comment by tinymachine** [comment]
Ah, fixes like correcting mistakes I introduce in my PRs? 😛 Sure, that would be great. FWIW, I'll only use admin privileges for that kind of fix; anything else, I'll check in with you first. Thanks!

**Pull request merged**
